Acq(0, raw)
TriggerMux(0)
dbLoadTemplate("db/acq.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=GEN, NELM=${NELM}, INDEX=0")
dbLoadRecords("db/raw_data.template", "P=${P1}, R=${R1}, ACQ_NAME=GEN, NELM=${NELM}, PORT=ACQ-0")
Acq(1, raw)
TriggerMux(1)
dbLoadTemplate("db/acq.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=GEN, NELM=${NELM}, INDEX=1")
dbLoadRecords("db/raw_data.template", "P=${P2}, R=${R2}, ACQ_NAME=GEN, NELM=${NELM}, PORT=ACQ-1")

Acq(2, raw)
TriggerMux(2)
dbLoadTemplate("db/acq.substitutions", "P=${P1}, R=${R1}, ACQ_NAME=PM, NELM=${NELM}, INDEX=2")
dbLoadRecords("db/raw_data.template", "P=${P1}, R=${R1}, ACQ_NAME=PM, NELM=${NELM}, PORT=ACQ-2")
Acq(3, raw)
TriggerMux(3)
dbLoadTemplate("db/acq.substitutions", "P=${P2}, R=${R2}, ACQ_NAME=PM, NELM=${NELM}, INDEX=3")
dbLoadRecords("db/raw_data.template", "P=${P2}, R=${R2}, ACQ_NAME=PM, NELM=${NELM}, PORT=ACQ-3")
