Acq(0, lamp)
TriggerMux(0)
dbLoadTemplate("db/acq.substitutions", "P=${P}, R=${R}, ACQ_NAME=LAMP, NELM=${NELM}, INDEX=0")
Acq(1, sysid)
TriggerMux(1)
dbLoadTemplate("db/acq.substitutions", "P=${P}, R=${R}, ACQ_NAME=SYSID, NELM=${NELM}, INDEX=1")
